extends Node


signal OnObjectLoaded(obj)
signal OnRequestObjectUnload(obj)
signal OnRequestLevelChange(level)
signal OnStartLoadLevel()
signal OnLevelLoaded()
signal OnLevelReady()
signal OnPlayerCreated(player)
signal OnAttributeAdded(obj, added_name)
signal OnCameraDragged()
signal OnCameraZoomed(new_zoom)
signal OnMovement(obj, dir)
signal OnMovementValidated(obj, dir)
signal OnPositionUpdated(obj)
signal OnBeginParallelAction(obj)
signal OnUseAP(obj, amount)
signal OnAPUsed(obj, amount) # To lock player input as soon as it has done an action (the action will be validated by the APBehavior in case of complex, parallel events)
signal OnEndParallelAction(obj)
signal OnUseEnergy(obj, amount)
signal OnEnergyChanged(obj)
signal OnObjTurn(obj)
signal OnLogLine(text, fmt)
signal OnDealDamage(targets, shooter, weapon_data, shot_tile) # fired before all other validations
signal OnShotFired(shot_tile, shooter, weapon_data) # for VFX
signal OnDamageTaken(target, shooter, damage_type) # only fired if damage is > 0
signal OnPickup(picker, picked)
signal OnObjectPicked(picker)
signal OnDropCargo(dropper, item_id, count)
signal OnDropMount(dropper, item_id, index)
signal OnRemoveMount(dropper, item_id, index)
signal OnEquipMount(equipper, slot_name, index, item_id)
signal OnAddItem(picker, item_id)
signal OnRemoveItem(holder, item_id, amount)
signal OnScannerUpdated(obj)
signal OnPlayerDeath()
signal OnObjectDestroyed(obj) # for vfx
signal OnRequestTargettingOverlay(player, targetting_data, callback_obj, callback_method)
signal OnTargetClick(click_pos, target_type)
signal OnWaitForAnimation()
signal OnAnimationDone()
signal OnTransferPlayer(old_player, new_player)
signal OnMountRemoved(obj, slot, src)
signal OnMountAdded(obj, slot, src)
signal OnClearMounts(obj)
signal OnClearCargo(obj)
signal OnReplaceMounts(obj, new_mounts)
signal OnReplaceCargo(obj, new_cargo)
signal OnUpdateCargoVolume(obj)
signal OnConsumeItem(obj, item_data)
signal OnTriggerAnomaly(obj, anomaly)
signal OnAnomalyEffectGone(obj, effect_data)
signal OnCrafting(crafter, result)
signal OnStatusChanged(obj)
signal OnDifficultyChanged(newdiff)
signal OnPlayerInputStateChanged(playerObj, inputState)
signal OnAddToAnimationQueue(callback_obj, callback_name, args, priority)

signal OnGUILoaded(name, obj)
signal OnPushGUI(name, init_param, transition_name)
signal OnPopGUI()
signal OnShowGUI(name, init_param, transition) # will not add the menu on the stack
signal OnHideGUI(name)
signal OnAddShortcut(key, obj, method)
signal OnRemoveShortcut(key, obj, method)
signal OnEnableShortcut(key, obj, method, isEnabled)
signal OnGUIChanged(current_menu)
signal OnHighlightUIElement(element_name)
signal OnResetHighlight()
signal OnHUDVisiblityChanged()
signal OnLocaleChanged()


func _ready():
	pass
